spring:
  profiles:
    include:
      - core
  boot:
    admin:
      client:
        url: "http://localhost:18080"
server:
  tomcat:
    accesslog:
      buffered: true
      directory: /event/logs/tomcat
      enabled: true
      pattern: "%{yyyy-MM-dd HH:mm:ss}t\t%s\t%r\t%a\t%h\t%D"
      request-attributes-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
