spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/events?useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USER:root}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _HISTORY
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE