spring:
  datasource:
    url: jdbc:mysql://localhost:3306/events?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: song9207108

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE